apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: s2s-validator
  namespace: gateways
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: s2s-ingress
  rules:
    authentication:
      vault-spiffe:
        jwt:
          jwksUrl: __NETWORKING_VAULT_ADDR__/v1/__NETWORKING_VAULT_SPIFFE_MOUNT__/.well-known/keys
          ttl: 300
        credentials:
          customHeader:
            name: x-np-token
    authorization:
      emisor-habilitado:
        patternMatching:
          patterns:
            - predicate: |
                auth.identity.iss == "__NETWORKING_VAULT_ISSUER__"
            - predicate: |
                auth.identity.sub == "__NETWORKING_VAULT_SPIFFE_SUB__"
    response:
      success: {}
