configuration:
#  TRAFFIC_CONTAINER_IMAGE: "136650373784.dkr.ecr.us-east-1.amazonaws.com/ecr-public/nullplatform/k8s-traffic-manager:latest"
  IMAGE_PULL_SECRETS:
    ENABLED: false
  CABANCO_MOUNTS:
    - name: cakeystore
      secretName: secret-cabanco-keystore
      mode: 420
      path: /opt/cabanco/keystore
      readOnly: true
    - name: caroot
      secretName: secret-cabanco-root
      mode: 420
      path: /opt/cabanco/caroot
      readOnly: true
    - name: caintermedia
      secretName: secret-cabanco-intermedia
      mode: 420
      path: /opt/cabanco/caintermedia
      readOnly: true
    - name: cabanco-chain
      secretName: secret-cabanco-chain
      mode: 420
      path: /opt/cabanco/cabanco-chain
      readOnly: true
