configuration:
  POM_SERVICES_LINK_SPECIFICATION_ID: 3daa410c-0068-49cf-ba87-170c561288b9
  POM_SERVICES_MOUNTS:
    - name: jwt-secret
      secretName: jwt-secret
      mode: 420
      path: /opt/jwt
      readOnly: true
