configuration:
  POM_SERVICES_LINK_SPECIFICATION_ID: 76aad5e0-aecf-48e3-80b1-be50bb8302c9
  POM_SERVICES_MOUNTS:
    - name: jwt-secret
      secretName: jwt-secret
      mode: 420
      path: /opt/jwt
      readOnly: true
