configuration:
  POM_SERVICES_LINK_SPECIFICATION_ID: c0d9a623-323d-4f4e-b010-0c4c33bf076b
  POM_SERVICES_MOUNTS:
    - name: jwt-secret
      secretName: jwt-secret
      mode: 420
      path: /opt/jwt
      readOnly: true
