apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: s2s-validator
  namespace: gateways
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: s2s-ingress
  rules:
    authentication:
      local-__APP_NAMESPACE__:
        jwt:
          jwksUrl: http://__LOCAL_JWKS_NAME__.kuadrant-system.svc.cluster.local:8080/__APP_NAMESPACE__/jwks.json
        credentials:
          customHeader:
            name: x-egress-token
    authorization:
      claims-esperados:
        patternMatching:
          patterns:
            - predicate: auth.identity.iss == "__EGRESS_ISSUER__"
            - predicate: auth.identity.src_namespace == "__APP_NAMESPACE__"
    response:
      success: {}
