apiVersion: v1
kind: Secret
metadata:
  name: secret-cabanco-keystore
type: Opaque
# Placeholder content — solo para que el volume monte. No es un keystore real.
stringData:
  keystore.jks: "placeholder-cabanco-keystore"
